// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1IRtg37h2D9YmRurAi6wcY0CzGOM3VS0',
    appId: '1:629408839686:web:cbdd8932b426e95bfaab87',
    messagingSenderId: '629408839686',
    projectId: 'apricotcomic-demo-5b9f3',
    authDomain: 'apricotcomic-demo-5b9f3.firebaseapp.com',
    storageBucket: 'apricotcomic-demo-5b9f3.appspot.com',
    measurementId: 'G-MBSQKP463Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrAQePq7x5J6GVBlUdVSR6E_hxU-CFbSI',
    appId: '1:629408839686:android:bf9ca231317eebdefaab87',
    messagingSenderId: '629408839686',
    projectId: 'apricotcomic-demo-5b9f3',
    storageBucket: 'apricotcomic-demo-5b9f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv-Zaukg3ztbEgKZDThckauNfLb8VZwcc',
    appId: '1:629408839686:ios:391ee1ae22a84718faab87',
    messagingSenderId: '629408839686',
    projectId: 'apricotcomic-demo-5b9f3',
    storageBucket: 'apricotcomic-demo-5b9f3.appspot.com',
    iosClientId: '629408839686-j8lufbp8o104tj98pijkkoml0rqgs5b1.apps.googleusercontent.com',
    iosBundleId: 'com.example.apricotcomicdemo',
  );
}
